# Generated by Django 4.1.3 on 2022-11-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addRequesterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesterName', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='RequesterData',
        ),
    ]
