# Generated by Django 4.1.3 on 2022-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_api', '0002_addrequesterdata_delete_requesterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='requesterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesterId', models.CharField(max_length=20, unique=True)),
                ('requesterName', models.CharField(max_length=30)),
                ('fromAddress', models.CharField(max_length=100)),
                ('toAddress', models.CharField(max_length=100)),
                ('Date_n_Time', models.DateTimeField(max_length=100)),
                ('noOfAssets', models.IntegerField()),
                ('assetSensitivity', models.CharField(choices=[('HIGHLY_SENSITIVE', 'HIGHLY_SENSITIVE'), ('SENSITIVE', 'SENSITIVE'), ('NORMAL', 'NORMAL')], max_length=20)),
                ('assetTypes', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('TRAVEL_BAG', 'TRAVEL_BAG'), ('PACKAGE', 'PACKAGE')], max_length=20)),
                ('whomToDeliver', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='riderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riderId', models.IntegerField(unique=True)),
                ('riderName', models.CharField(max_length=30)),
                ('fromAddress', models.CharField(max_length=100)),
                ('toAddress', models.CharField(max_length=100)),
                ('Date_n_Time', models.DateTimeField(max_length=100)),
                ('travelMedium', models.CharField(choices=[('BUS', 'BUS'), ('CAR', 'CAR'), ('TRAIN', 'TRAIN')], max_length=30)),
                ('noOfAssets', models.IntegerField()),
                ('status', models.CharField(default='NOT APPLIED', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='addRequesterData',
        ),
    ]
