# Generated by Django 4.1.3 on 2022-11-19 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_api', '0004_remove_requesterdata_date_n_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesterdata',
            name='Date_n_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
