# Generated by Django 4.1.3 on 2022-11-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_api', '0005_requesterdata_date_n_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesterdata',
            name='requesterId',
            field=models.CharField(max_length=20),
        ),
    ]
