# Generated by Django 4.1.3 on 2022-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_api', '0006_alter_requesterdata_requesterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderdata',
            name='riderId',
            field=models.IntegerField(),
        ),
    ]
